version: '3'
services:
  dns:
    image: adguard/adguardhome:latest
    ports:
      - '53:53/tcp'
      - '53:53/udp'
    networks:
      - lab5_network
    restart: unless-stopped
    volumes:
      - volume_dns_work:/opt/adguardhome/work
      - volume_dns_conf:/opt/adguardhome/conf
    cpus: '0.5'
    mem_limit: 512M
    hostname: dns

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf/app.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/ssl
    networks:
      - lab5_network
    depends_on:
      - dns
      - registry
    cpus: '1'
    mem_limit: 1G
    hostname: web

  registry:
    image: registry:2
    hostname: registry
    networks:
      - lab5_network
    cpus: '0.5'
    mem_limit: 1G
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
    volumes:
      - ./auth:/auth
    restart: unless-stopped
    depends_on:
      - dns

networks:
  lab5_network:

volumes:
  volume_dns_work:
  volume_dns_conf:
  registry_auth:
