services:
  agent:
    image: portainer/agent
    deploy:
      mode: global
      placement:
        constraints: 
          - node.platform.os == linux
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /etc/localtime:/etc/localtime
    networks:
      - agent_network
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent

  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    deploy:
      placement:
        constraints:
          - node.hostname == manager1
    volumes:
      - portainer_data:/data
      - /etc/localtime:/etc/localtime
    networks:
      - agent_network
    ports:
      - 1102:9000

volumes:
  portainer_data:

networks:
  agent_network:
    driver: overlay
