services:
  web:
    image: itzg/web-debug-server
    deploy:
      mode: global
    ports:
      - "8080:8080"
    networks:
      - web_network

  nginx:
    image: nginx
    depends_on:
      - web
    ports:
      - "1103:80"
    deploy:
      placement:
        constraints: 
          - node.hostname == manager1 
    networks:
      - web_network
    volumes:
      - nginx.conf:/etc/nginx/nginx.conf

networks:
  web_network:
    driver: overlay
